% Facts
girl('Maria').
girl('Julia').
girl('Sophia').
girl('Emma').
girl('Olivia').
girl('Ava').
girl('Isabella').
girl('Mia').
girl('Charlotte').
girl('Amelia').
girl('Evelyn').
girl('Abigail').
girl('Harper').
girl('Emily').
girl('Elizabeth').
girl('Avery').
girl('Sofia').
girl('Ella').
girl('Scarlett').
girl('Grace').
girl('Chloe').
girl('Victoria').
girl('Riley').
girl('Aria').
girl('Lily').
girl('Aubrey').
girl('Zoey').
girl('Penelope').
girl('Lillian').
girl('Addison').
girl('Layla').
girl('Natalie').
girl('Camila').
girl('Hannah').
girl('Brooklyn').
girl('Zoe').
girl('Nora').
girl('Leah').
girl('Savannah').
girl('Audrey').
girl('Claire').
girl('Eleanor').
girl('Skylar').
girl('Ellie').
girl('Samantha').
girl('Stella').
girl('Paisley').
girl('Violet').
girl('Mila').
girl('Allison').
girl('Alexa').
girl('Hazel').

beautiful('Maria').
beautiful('Julia').
beautiful('Emma').
beautiful('Olivia').
beautiful('Sophia').
beautiful('Ava').
beautiful('Isabella').
beautiful('Mia').
beautiful('Charlotte').
beautiful('Amelia').
beautiful('Ella').
beautiful('Sofia').
beautiful('Lily').
beautiful('Hannah').
beautiful('Nora').
beautiful('Eleanor').
beautiful('Stella').
beautiful('Hazel').

smart('Emma').
smart('Sophia').
smart('Isabella').
smart('Mia').
smart('Evelyn').
smart('Abigail').
smart('Elizabeth').
smart('Avery').
smart('Ella').
smart('Grace').
smart('Victoria').
smart('Aria').
smart('Lillian').
smart('Natalie').
smart('Camila').
smart('Nora').
smart('Audrey').
smart('Eleanor').
smart('Samantha').

slim('Sophia').
slim('Olivia').
slim('Ava').
slim('Charlotte').
slim('Amelia').
slim('Ella').
slim('Grace').
slim('Chloe').
slim('Victoria').
slim('Lily').
slim('Zoey').
slim('Addison').
slim('Layla').
slim('Natalie').
slim('Savannah').
slim('Claire').
slim('Ellie').
slim('Samantha').
slim('Stella').
slim('Mila').

fat('Maria').
fat('Julia').
fat('Harper').
fat('Emily').
fat('Aubrey').
fat('Penelope').
fat('Brooklyn').
fat('Zoe').
fat('Leah').
fat('Skylar').
fat('Paisley').
fat('Violet').
fat('Allison').
fat('Alexa').

tall('Maria').
tall('Sophia').
tall('Charlotte').
tall('Grace').
tall('Victoria').
tall('Eleanor').

short('Mia').
short('Emily').
short('Ella').
short('Zoe').
short('Lillian').
short('Natalie').
short('Charlotte').

weird('Samantha').
weird('Zoe').
weird('Hazel').
weird('Paisley').

% Rules
is_cute(X) :- girl(X), beautiful(X), short(X).
is_beautifil(X) :- girl(X), beautiful(X).
is_smart_and_beautiful(X) :- girl(X), smart(X), beautiful(X).
is_fat_and_cute(X) :- girl(X), fat(X), beautiful(X).